### ISSUE TITLE
Need to configure Terraform tools

### ISSUE THREAD

**Issue by cosckoya** [cosckoya/.dotfiles#6]
It's required to add some terraform tools to the automated installation.

Some tools are required to work with diferent hooks, compliances and deploy: tflint, tfsec and terraform-docs.

**Comment by rusoblanco** [comment]
Yo! I just made some changes on your repo. Adding some Terraform tools, reviewing README and pre-commit files.

Have a look ;)

**Comment by cosckoya** [comment]
Nice! I just merged your PRs to the repository, they work fine.

Thanks
